---
title: "Urticina mapping"
fontfamily: mathpazo
fontsize: 10pt
output:
  pdf_document:
    toc: no
  html_document:
    df_print: paged
    toc: no
layout: topic
geometry: margin=0.75in
editor_options:
  chunk_output_type: console
---


```{r include = FALSE, cache = FALSE}
# This code block sets up the r session when the page is rendered to html

# Change general options
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, include = TRUE, results = "hide", 
                      message = FALSE, warning = FALSE, 
                      cache = FALSE, par = FALSE)

# Set up figure options
knitr::opts_chunk$set(fig.align = 'center', fig.show = 'asis', 
                      fig.width = 3.5, fig.height = 3.5) # default fig sizes

# Set the web address where R will look for files from this repository
repo_url <- "https://raw.githubusercontent.com/elahi/kfe/master/"

# Define the directory where images generated by knit will be saved
# knitr::opts_chunk$set(fig.path = "/images/",
#                       cache.path = "/cache/")

library(tidyverse)
theme_set(theme_bw())
library(knitr)

# Set working directory
knitr::opts_knit$set(root.dir = "../")
```

Load the data and prep for mapping. 

```{r}
library(tidyverse)
theme_set(theme_bw())
dat <- read_csv("data/urticina_mapping_data - Sheet1.csv")
dat <- dat %>% 
  mutate(x = ifelse(east_west == "east", 
                    distance_cable_cm/100, 
                    -distance_cable_cm/100), 
         y = distance_tag_cm/100 + reference_tag)
```

Is the measured circumference similar to an estimated circumference (calculated from the diameter)?

```{r}
dat <- dat %>%
   mutate(circum_calc = 2 * pi * diameter_cm/2, 
          area_cm2 = pi * (diameter_cm/2)^2)
dat %>% 
  ggplot(aes(circum_cm, circum_calc)) + 
  geom_point() + 
  geom_abline(aes(slope = 1, intercept = 0), linetype = 2) + 
  geom_smooth(method = "lm") + 
  labs(x = "Circumference - measured (cm)", 
       y = "Circumference - estimated from radius (cm)")
```

Map of *Urticina piscivora* at Hopkins Marine Life Refuge permanent cable. 

```{r, fig.width = 7, fig.height = 7}
dat %>%
  ggplot(aes(x = x, y = y, color = dive, size = area_cm2)) + 
  geom_vline(aes(xintercept = 0), size = 2, color = "gray") + 
  geom_vline(aes(xintercept = 0), size = 0.5, color = "black", linetype = 2) + 
  geom_hline(aes(yintercept = 100), size = 0.5, color = "black", linetype = 2) + 
  labs(x = "Distance due east/west from cable (m)", 
       y = "Distance along cable (m)") + 
  geom_point(alpha = 0.5) + 
  scale_size_area()
```


